### ISSUE TITLE
direct option to print PDF from reveal slideshow

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#148]
Creating an issue as per discussion during BH Arsenal.

reveal.js allows direct pdf printing. why not add a button to ensure user can quickly get a printable pdf from presentation.

**Comment by BuffaloWill** [comment]
@anantshri mind taking a look at https://github.com/SerpicoProject/Serpico/pull/149/files? This should add the functionality. However, I am running into some trouble with the print-pdf functionality in reveal.js. Specifically in Chrome 52 on OS X, the presentation comes up blank. Since you are familiar with reveal,js, could you take a look? Thanks!

**Comment by anantshri** [comment]
Hey @BuffaloWill I had a look at this. There is something wrong in our Javascript runtime css selection code. if you manually specific paper or pdf.css it all works just fine.

I will give it another shot later today to see if this can be easily solved.

**Comment by BuffaloWill** [comment]
Landed in https://github.com/SerpicoProject/Serpico/commit/9f76c18d1b3b88ab587b396fef63852d2ac096c9
