### ISSUE TITLE
Incorrectly Escaped Characters

### ISSUE THREAD

**Issue by 0xffe4** [SerpicoProject/Serpico#237]
Bug

-------------------
## Bug
When editing a finding, if the finding title includes certain characters (e.g. <, >, &, etc.) they are being escaped.

1. Click edit on a finding with an affected character in the Title field (e.g. "SSL/TLS EXPORT_RSA <= 512-bit Cipher Suites Supported (FREAK)")
2. In the Title field on the edit form, the name will now display as "SSL/TLS EXPORT_RSA &amp;lt;= 512-bit Cipher Suites Supported (FREAK)" with the < being replaced with &amp;lt;
3. Subsequent edits/saves will continue the trend by escaping the & and replacing with &amp; so the title would now appear as "SSL/TLS EXPORT_RSA &amp;amp;lt;= 512-bit Cipher Suites Supported (FREAK)"

**Comment by BuffaloWill** [comment]
Just pushed a fix for this. Decided not to encode &gt; as > when presenting the title to the user for editing due to XSS concerns. However, the subsequent edit and save problem of & degenerating into &amp; should be fixed. I think this is a reasonable compromise. On most other pages the > is still presented properly and there isn't an issue of the title changing with multiple edits.
