### ISSUE TITLE
Markup Language does not work as expected

### ISSUE THREAD

**Issue by Bevilacqua** [SerpicoProject/Serpico#314]
## Bug
Using markup when creating a new finding does not work as expected. To recreate:
1. Add a new finding
2. Use italic markdown for part of an entry EX:
`dfwefefwef [~~ italics ~~] dawfbqr`
3. Preview the document.

The preview is all italic instead of just the part wrapped in `[~~`
![20427638_2051137351774889_1736126867_n](https://user-images.githubusercontent.com/1688796/28706110-2d118236-73b6-11e7-90e8-f44213f06a65.png)

**Comment by kelvinsilva** [comment]
ii have this issue also

**Comment by kelvinsilva** [comment]
@BuffaloWill @arisada @ccammilleri @sho-luv

**Comment by BuffaloWill** [comment]
Thanks @Bevilacqua I will test this out today.

**Comment by BuffaloWill** [comment]
Because italics (and markup in general) are applied at a paragraph element I am not sure about the best approach to solving this. I can update the explanation to indicate that the entire paragraph will be italicized instead of a word or sentence. There might be a way with the markup language to get Word to apply only to a portion of the paragraph but I can't confirm. Closing this for now and will update the markup summary modal window. Please feel free to submit a PR if you find an alternate solution.
