### ISSUE TITLE
CVSS2 scoring missing slash on high, critical and medium issues. 

### ISSUE THREAD

**Issue by kafetz** [SerpicoProject/Serpico#414]
Upon generating a report into MS Word from Serpico, the CVSSv2 scoring is missing a slash, for example, see below, this does not appear to be a template issue as the entire CVSS string is imported as a single object opposed to each element independently. :

CVSS:2.0/AC:L/AU:N/AV:N/**C:CI:N**/I:P/E:H/RL:U/RC:C/TD:H/CR:M/IR:M/AR:M

Highlighted in bold is where the slash is missing. 
--

**Comment by MaxNad** [comment]
You are right. However, this only applies to the C:C value.

If you look at the code in helper.rb you will see that this value is assigned like this :
```c2_vs += "C:C"```

While others are assigned like this :
```c2_vs += "C:N/"```

If you are able to fix that yourself and make a PR, go ahead. Otherwise, I will be making the change as soon as I have a bit of time.

Thank you for reporting this.

**Comment by kafetz** [comment]
Hi, thanks for confirming, I am not yet familiar with the code so not comfortable making the change myself, sorry for adding to your workload. 

Jed 

On Feb 08, 2018, at 05:06 AM, Maxime Nadeau <notifications@github.com> wrote:

You are right. However, this only applies to the C:C value.

If you look at the code in helper.rb you will see that this value is assigned like this :
c2_vs += "C:C"

While others are assigned like this :
c2_vs += "C:N/"

If you are able to fix that yourself and make a PR, go ahead. Otherwise, I will be making the change as soon as I have a bit of time.

Thank you for reporting this.
