### ISSUE TITLE
I want to add NIST800-30 to the 

### ISSUE THREAD

**Issue by sho-luv** [SerpicoProject/Serpico#435]
# I'm trying to add a the following feature:

New Vuln Rating of NIST800-30

<img width="722" alt="screen shot 2018-03-23 at 2 18 45 pm" src="https://user-images.githubusercontent.com/1679089/37857746-ff7dc49a-2eba-11e8-9c94-a529020236c4.png">

So when I go into the findings section I can set two variables Likelihood, and Impact.

Based on that I'll get a Risk rating based on the above matrix. 

I'm looking at how CVSSv3 was added and I'm checking out the files that were edited:

grep -ilr "cvssv3"
views/findings_edit.haml
views/config.haml
views/create_finding.haml
views/findings_list.haml
scripts/first_time.rb
db/master.db
routes/master.rb
routes/report.rb
routes/admin.rb
model/master.rb
public/js/cvsscalc30.js
helpers/asciidoc_exporter.rb
helpers/helper.rb

Am I going about this in the right way? Or should I just try to do this with user defined variables?

**Comment by sho-luv** [comment]
... I think I can just modify the RiskMatrix to accomplish this. Trying that.

**Comment by BuffaloWill** [comment]
Yes, I agree risk matrix close and you might get away with just editing the fields for that. 

To add a new scoring algorithm in general, you would need to do the following:
1. Update model/master.rb so that the correct columns are created in the db and the object fields are accessible in the application.
2. Update the views/* to reflect the new scoring option in the UI.
3. Update the routes/* if there are any calculations that need to be done with the score. Otherwise Serpico should save the data for you without fuss.

I hope that helps.

**Comment by BuffaloWill** [comment]
Closing the issue, conversation moved to Slack.

**Comment by djphenom** [comment]
Hi There,
I was looking at this sort of calculation as well.  Did you guys come to a resolution or way to do this?
Thanks.
