### ISSUE TITLE
Replace <<customer>> with <<short_company_name>> in findings and templates

### ISSUE THREAD

**Issue by UrfinJusse** [SerpicoProject/Serpico#440]
I'm using a stock install of Serpico 1.2.2.1 running on a vanilla Debian 9. No modifications to the Serpico, I'm using a default "Open Mail Relay Identified" finding with a default "Default Template - Generic Risk Scoring" template.

As per the "Overview" cheatsheet, the <<CUSTOMER>> tag within the finding is supposed to be replaced with the company name in the final report.

Unfortunately, this is not the case:

![screen shot 2018-04-12 at 4 42 18 pm](https://user-images.githubusercontent.com/18199383/38703162-7d1dc8f4-3e70-11e8-81c2-44ae63073fa6.png)

Company's information is all filled out:

![screen shot 2018-04-12 at 4 45 47 pm](https://user-images.githubusercontent.com/18199383/38703329-fd582a00-3e70-11e8-9df2-a849f40237df.png)

Is this a known bug?

**Comment by frisch-raphael** [comment]
The issue here is that the overview and the default templates aren't up-to-date.
Instead of <<customer>>, you should use <<short_company_name>> or <<full_company_name>>. Actually, you can use any report variable in this way.

In my opinion, while this isn't a bug, the issue shouldn't be closed until the overview and the templates are updated, or better yet, another issue should be opened.

**Comment by UrfinJusse** [comment]
Thank you frisch-raphael - that works!

Interestingly enough, I was pretty close to discovering it when I tried ΩFULL_COMPANY_NAMEΩ but I used "omegas" instead of <<>>.

**Comment by BuffaloWill** [comment]
Updating the title of the issue. I agree with @frisch-raphael. this should be fixed in the overview and the findings.
