### ISSUE TITLE
MSFRPC Integration

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [SerpicoProject/Serpico#451]
# Please fill out the Bug Form or Feature Request Below

-------------------

I have setup and configured the RPC connection as shown on the wiki, yet when I go to view hosts, I keep being told that I am not authenticated. I followed everything step by step and even attempted to use "load msgrpc" through the msfconsole and still to no avail. Is there something I am missing or information I could give to help resolve this problem.

**Comment by ccammilleri** [comment]
A few things to keep in mind.

1. make sure you have matching workspaces
2. only use supported ruby versions
3. are you able to see the network traffic between applications?
4. have you restarted serpico since you've enabled the vulnmaping feature?

if none of that helps let me know your metasploit version and i can see if i can recreate.

**Comment by ccammilleri** [comment]
it could be possible that you are experiencing #424

**Comment by BuffaloWill** [comment]
@SchellerCyberSecurity try downgrading to 1.2.1. There is an issue with msf integration in current branch; 424 as @ccammilleri said.

**Comment by SchellerCyberSecurity** [comment]
I still seem to be having the issue, not sure if I downgraded correctly. I
ran dpkg -r serpico then after downloading 1.2.1 dpkg -i
serpico_1.2.1_amd64.deb


Derek M Scheller Jr
CCNA R/S, CCNA-Security, CISSP, CEH, CPT, GSEC, GCED, GCIH, GPYC
Cell: 443-805-0239
https://schellercybersecurity.com/blog

**Comment by BuffaloWill** [comment]
This should be followed in https://github.com/SerpicoProject/Serpico/issues/424
