### ISSUE TITLE
Using conditional in tables

### ISSUE THREAD

**Issue by Elorcen** [SerpicoProject/Serpico#531]
Hi,

I am currently trying to use Serpico, and I encountered an issue I cannot solve.

So, for example, I list my findings with its attributes:

```
¬report/findings_list/findings:::CVSS_Total>=9¬
... some other lines ...
∆
```

And it works well. Now I use conditionals for findings as it is documented [here](https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report#string-comparison-for-finding-variable): 

```
¬report/findings_list/findings:::CVSS_Total>=9¬
... some other lines ...

† √ +availability:::High √ †
Elevé
¥

∆
```

Again, it works as intended. However I have a need which is having this conditional in a table (for formatting goals) but when I put these 3 lines in a cell, the Word document is considered corrupted or damaged after generating the document.

I tried with these lines as well, just in case:

```
† translate(availability,$up,$low)=translate('High',$up,$low) †
Elevé
¥
```

But same issue as the previous conditional, it works when it is out of the table, but inside a cell, it corrupts the Word document post-creation.

Does someone know what I am doing wrong here ?

Kind regards

**Comment by BuffaloWill** [comment]
@Elorcen Have you tried the table string comparison in the wiki (https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report#classic-string-comparison): 
```
æreport/findings_list/findings:::risk<5:::translate(assessment_type,$up,$low)=translate('external',$up,$low)æ ∞title∞
```

This particular comparison (table string comparison inside of one or more for loops) has given us trouble before but hopefully that helps.

**Comment by N0fix** [comment]
The string comparaison of the wiki `æreport/findings_list/findings:::risk<5:::translate(assessment_type,$up,$low)=translate('external',$up,$low)æ ∞title∞` is giving me blank rows, while this works when there is only one column : 
`¬report/findings_list/findings:::CVSS_Total>=9¬
... some other lines ...

† √ +availability:::High √ †
Elevé
¥

∆`
I still can't do conditions in any table because of that. Is there any workaround? 

Note : the classic 
`† √ +availability:::High √ †
Elevé
¥`
makes my docx crash.
