### ISSUE TITLE
Saved findings are not listed in add from template list

### ISSUE THREAD

**Issue by mehmethafif** [SerpicoProject/Serpico#561]
-------------------
## Bug
A finding is created within a report from create finding navbar then I use button to upload it to database. Response is succesful but it becomes red in findings database and it is not listed in findings template when adding to a report.

1. in report finding created
2. finding uploaded to database
3. finding is not present in add finding from template list
4. finding is present at finding database in red row.
5. so cant reuse created finding
![1](https://user-images.githubusercontent.com/32527467/57961355-1250ba80-7917-11e9-85fe-24cd9161d70d.JPG)
![2](https://user-images.githubusercontent.com/32527467/57961356-15e44180-7917-11e9-8d95-b17e0f7a8826.JPG)
![3](https://user-images.githubusercontent.com/32527467/57961357-18469b80-7917-11e9-905e-8e57e9702275.JPG)
![4](https://user-images.githubusercontent.com/32527467/57961358-1a105f00-7917-11e9-90aa-d6aadc915332.JPG)

**Comment by BuffaloWill** [comment]
Hi @mehmethafif. Thank you for the detailed submission. This is by design. After adding a new finding to the database you will need to click on the edit button and check "Approve Finding".

This feature ensures that if a user attempts to add a finding from their report to the database that an administrator has a chance to review it before it is available to everyone.
